version: '3.4'
services:
  mymy:
    image: mymy
    ports:
      - '5004:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: mymy
    build:
      context: .
      dockerfile: mymy/Dockerfile
  